name: Dependencies

on: [push, pull_request]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Test main pyproject.toml up to date
        run: |
          poetry self add poetry-plugin-up
          poetry up --latest
          git add pyproject.toml
          git diff --cached --exit-code

      - name: Test main pre-commit up to date
        run: |
          poetry run pre-commit autoupdate
          git add .pre-commit-config.yaml
          git diff --cached --exit-code
