name: Schedule

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '30 5 * * 2,5'

jobs:
  build-poetry:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Init git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"

    - name: Test pyproject.toml up to date
      run : |
        poetry self add poetry-plugin-up
        poetry up --latest
        git add pyproject.toml
        git diff --cached --exit-code

    - name: Test pre-commit up to date
      run : |
        poetry run pre-commit autoupdate
        git add .pre-commit-config.yaml
        git diff --cached --exit-code

    - name: Test pre-commit up to date in template
      run: poetry run pytest tests/test_bake_project.py::test_pre_commit_up_to_date
