name: Update example project

on:
  workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Generate example
      run: poetry run python .github/python/generate_example.py

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'cookiecutter-example'
        destination-github-username: 'baptiste-pasquier'
        destination-repository-name: 'cookiecutter-example'
        user-email: '41898282+github-actions[bot]@users.noreply.github.com'
        user-name: 'github-actions[bot]'
        target-branch: main
        commit-message: ':robot: Update from ORIGIN_COMMIT'
